#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [2]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Abhishek','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
# print(df)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

       Name  Age       City
0  Abhishek   25  Bangalore
1      John   30   New York
2      Jack   45    Florida

In [7]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Abhishek','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)

print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

       Name  Age       City
0  Abhishek   32  Bangalore
1      John   34  Bangalore
2     Bappy   32  Bangalore
3      JAck   32  Bangalore

In [8]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [9]:
df.describe()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
count,481,480,480,480,480,480,480,480,480
unique,242,241,7,233,8,118,174,4,4
top,10001,2024-01-01,Electronics,Dyson Supersonic Hair Dryer,1,49.99,299.99,North America,Credit Card
freq,2,2,80,4,194,18,10,160,239

In [ ]:
df.info()

In [ ]:
df.tail(5)

In [ ]:
### Accessing Data From Dataframe
df

In [ ]:
df['Name']

In [ ]:
df.loc[0]

In [ ]:
df.iloc[0]

In [ ]:
df

In [ ]:
## Accessing a specified element
df.at[2,'Age']

In [ ]:
df.at[2,'Name']

In [ ]:
## Accessing a specified element using iat
df.iat[2,2]

In [ ]:
df

In [ ]:
### Data MAnipulation with Dataframe
df

In [ ]:
## Adding a column
df['Salary']=[50000,60000,70000,75000]
df

In [ ]:
df

In [ ]:
## Remove a column
df.drop('Salary',axis=1, inplace=True)

In [ ]:
df

In [ ]:
## Add age to the column
df['Age']=df['Age']+1
df

In [ ]:
df.drop(0,inplace=True)

In [ ]:
df

In [ ]:
df=pd.read_csv('sales_data.csv')
df.head(5)

In [ ]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

In [ ]:
df.describe()

In [ ]:
print(df.dtypes)